spring:
  datasource:
    url: jdbc:postgresql://db:5432/heating
    username: heating
    password: heating
  jpa:
    hibernate:
      ddl-auto: none

logging:
  level:
    root: INFO
    ru.lct.heating: DEBUG
